-- MySQL Script generated by MySQL Workbench
-- Sun Apr 14 23:44:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tainia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tainia` (
  `Titlos` VARCHAR(45) NOT NULL,
  `Etos paragwghs` INT NOT NULL,
  `Xwra proeleusis` VARCHAR(45) NOT NULL,
  `Etaireia paragwghs` VARCHAR(45) NOT NULL,
  `Xronikh diarkeia` INT NOT NULL,
  `Eidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Titlos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Egxwria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Egxwria` (
  `Tainia_Titlos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tainia_Titlos`),
  INDEX `fk_Εγχώρια_Ταινία1_idx` (`Tainia_Titlos` ASC) VISIBLE,
  CONSTRAINT `fk_Εγχώρια_Ταινία1`
    FOREIGN KEY (`Tainia_Titlos`)
    REFERENCES `mydb`.`Tainia` (`Titlos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skhniko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skhniko` (
  `idSkhniko` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSkhniko`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diethnis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diethnis` (
  `Tainia_Titlos` VARCHAR(45) NOT NULL,
  `Skhniko_idSkhniko` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tainia_Titlos`),
  INDEX `fk_Διεθνής_Ταινία1_idx` (`Tainia_Titlos` ASC) VISIBLE,
  INDEX `fk_Διεθνής_Σκηνικό1_idx` (`Skhniko_idSkhniko` ASC) VISIBLE,
  CONSTRAINT `fk_Διεθνής_Ταινία1`
    FOREIGN KEY (`Tainia_Titlos`)
    REFERENCES `mydb`.`Tainia` (`Titlos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Διεθνής_Σκηνικό1`
    FOREIGN KEY (`Skhniko_idSkhniko`)
    REFERENCES `mydb`.`Skhniko` (`idSkhniko`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Keimeno grafhs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Keimeno grafhs` (
  `idKeimeno grafhs` LONGTEXT NOT NULL,
  `Keimeno grafhs_idKeimeno grafhs` LONGTEXT NULL,
  PRIMARY KEY (`idKeimeno grafhs`),
  INDEX `fk_Κείμενο γραφής_Κείμενο γραφής1_idx` (`Keimeno grafhs_idKeimeno grafhs` ASC) VISIBLE,
  CONSTRAINT `fk_Κείμενο γραφής_Κείμενο γραφής1`
    FOREIGN KEY (`Keimeno grafhs_idKeimeno grafhs`)
    REFERENCES `mydb`.`Keimeno grafhs` (`idKeimeno grafhs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Senario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Senario` (
  `idSenario` LONGTEXT NOT NULL,
  `Keimeno grafhs_idKeimeno grafhs` LONGTEXT NOT NULL,
  PRIMARY KEY (`idSenario`, `Keimeno grafhs_idKeimeno grafhs`),
  INDEX `fk_Σενάριο_Κείμενο γραφής1_idx` (`Keimeno grafhs_idKeimeno grafhs` ASC) VISIBLE,
  CONSTRAINT `fk_Σενάριο_Κείμενο γραφής1`
    FOREIGN KEY (`Keimeno grafhs_idKeimeno grafhs`)
    REFERENCES `mydb`.`Keimeno grafhs` (`idKeimeno grafhs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skinothetis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skinothetis` (
  `idSkinothetis` INT NOT NULL AUTO_INCREMENT,
  `Onomatepwnymo` VARCHAR(45) NOT NULL,
  `Hlikia` INT NOT NULL,
  `Pontoi` INT NOT NULL,
  `Egxwria_Tainia_Titlos` VARCHAR(45) NOT NULL,
  `Diethnis_Tainia_Titlos` VARCHAR(45) NOT NULL,
  `Senario_idSenario` LONGTEXT NOT NULL,
  PRIMARY KEY (`idSkinothetis`),
  INDEX `fk_Σκηνοθέτης_Εγχώρια1_idx` (`Egxwria_Tainia_Titlos` ASC) VISIBLE,
  INDEX `fk_Σκηνοθέτης_Διεθνής1_idx` (`Diethnis_Tainia_Titlos` ASC) VISIBLE,
  INDEX `fk_Σκηνοθέτης_Σενάριο1_idx` (`Senario_idSenario` ASC) VISIBLE,
  CONSTRAINT `fk_Σκηνοθέτης_Εγχώρια1`
    FOREIGN KEY (`Egxwria_Tainia_Titlos`)
    REFERENCES `mydb`.`Egxwria` (`Tainia_Titlos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Σκηνοθέτης_Διεθνής1`
    FOREIGN KEY (`Diethnis_Tainia_Titlos`)
    REFERENCES `mydb`.`Diethnis` (`Tainia_Titlos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Σκηνοθέτης_Σενάριο1`
    FOREIGN KEY (`Senario_idSenario`)
    REFERENCES `mydb`.`Senario` (`idSenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skinothetis_SkinothetisProtypo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skinothetis_SkinothetisProtypo` (
  `Skinothetis_idSkinothetis` INT NOT NULL,
  `Skinothetis_idSkinothetis1` INT NOT NULL,
  PRIMARY KEY (`Skinothetis_idSkinothetis`, `Skinothetis_idSkinothetis1`),
  INDEX `fk_Σκηνοθέτης_has_Σκηνοθέτης_Σκηνο_idx` (`Skinothetis_idSkinothetis1` ASC) VISIBLE,
  INDEX `fk_Σκηνοθέτης_has_Σκηνοθέτης_Σκηνο_idx1` (`Skinothetis_idSkinothetis` ASC) VISIBLE,
  CONSTRAINT `fk_Σκηνοθέτης_has_Σκηνοθέτης_Σκηνοθ`
    FOREIGN KEY (`Skinothetis_idSkinothetis`)
    REFERENCES `mydb`.`Skinothetis` (`idSkinothetis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Σκηνοθέτης_has_Σκηνοθέτης_Σκηνοθ1`
    FOREIGN KEY (`Skinothetis_idSkinothetis1`)
    REFERENCES `mydb`.`Skinothetis` (`idSkinothetis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skinothetis_SkinothetisFilos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skinothetis_SkinothetisFilos` (
  `Skinothetis_idSkinothetis` INT NOT NULL,
  `Skinothetis_idSkinothetis1` INT NOT NULL,
  PRIMARY KEY (`Skinothetis_idSkinothetis`, `Skinothetis_idSkinothetis1`),
  INDEX `fk_Σκηνοθέτης_has_Σκηνοθέτης_Σκηνο_idx` (`Skinothetis_idSkinothetis1` ASC) VISIBLE,
  INDEX `fk_Σκηνοθέτης_has_Σκηνοθέτης_Σκηνο_idx1` (`Skinothetis_idSkinothetis` ASC) VISIBLE,
  CONSTRAINT `fk_Σκηνοθέτης_has_Σκηνοθέτης_Σκηνοθ2`
    FOREIGN KEY (`Skinothetis_idSkinothetis`)
    REFERENCES `mydb`.`Skinothetis` (`idSkinothetis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Σκηνοθέτης_has_Σκηνοθέτης_Σκηνοθ3`
    FOREIGN KEY (`Skinothetis_idSkinothetis1`)
    REFERENCES `mydb`.`Skinothetis` (`idSkinothetis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Polh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Polh` (
  `Onoma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Onoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Xwra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Xwra` (
  `Onoma` VARCHAR(45) NOT NULL,
  `Polh_Onoma` VARCHAR(45) NOT NULL,
  `Skhniko_idSkhniko` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Onoma`),
  INDEX `fk_Χώρα_Πόλη1_idx` (`Polh_Onoma` ASC) VISIBLE,
  INDEX `fk_Χώρα_Σκηνικό1_idx` (`Skhniko_idSkhniko` ASC) VISIBLE,
  CONSTRAINT `fk_Χώρα_Πόλη1`
    FOREIGN KEY (`Polh_Onoma`)
    REFERENCES `mydb`.`Polh` (`Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Χώρα_Σκηνικό1`
    FOREIGN KEY (`Skhniko_idSkhniko`)
    REFERENCES `mydb`.`Skhniko` (`idSkhniko`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Xorhgos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Xorhgos` (
  `idXorhgos` VARCHAR(45) NOT NULL,
  `Xrhmatiko poso` INT NOT NULL,
  PRIMARY KEY (`idXorhgos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ithopoios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ithopoios` (
  `Photografia` BLOB NOT NULL,
  `Onomatepwnymo` VARCHAR(45) NOT NULL,
  `Hmeromhnia gennhshs` DATE NOT NULL,
  PRIMARY KEY (`Photografia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Xaraktiristiko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Xaraktiristiko` (
  `Onoma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Onoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fysiko xaraktiristiko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fysiko xaraktiristiko` (
  `Xaraktiristiko_Onoma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Xaraktiristiko_Onoma`),
  CONSTRAINT `fk_Φυσικό χαρακτηριστικό_Χαρακτηρ1`
    FOREIGN KEY (`Xaraktiristiko_Onoma`)
    REFERENCES `mydb`.`Xaraktiristiko` (`Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pneumatiko xaraktiristiko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pneumatiko xaraktiristiko` (
  `Xaraktiristiko_Onoma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Xaraktiristiko_Onoma`),
  CONSTRAINT `fk_Πνευματικό χαρακτηριστικό_Χαρα1`
    FOREIGN KEY (`Xaraktiristiko_Onoma`)
    REFERENCES `mydb`.`Xaraktiristiko` (`Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Texniko xaraktiristiko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Texniko xaraktiristiko` (
  `Xaraktiristiko_Onoma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Xaraktiristiko_Onoma`),
  CONSTRAINT `fk_Τεχνικό χαρακτηριστικό_Χαρακτη1`
    FOREIGN KEY (`Xaraktiristiko_Onoma`)
    REFERENCES `mydb`.`Xaraktiristiko` (`Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Programma ekpaidefsis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Programma ekpaidefsis` (
  `idProgramma ekpaidefsis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProgramma ekpaidefsis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Symbolaio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Symbolaio` (
  `idSymbolaio` VARCHAR(45) NOT NULL,
  `Hmeromhnia enarxis` DATE NOT NULL,
  `Hmeromhnia lhxhs` DATE NOT NULL,
  `Ethsies apolabes` INT NOT NULL,
  PRIMARY KEY (`idSymbolaio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagwnistikh diorganwsh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagwnistikh diorganwsh` (
  `Onoma` VARCHAR(45) NOT NULL,
  `Xwra dieksagwghs` VARCHAR(45) NOT NULL,
  `Hmeromhnia dieksagwghs` DATE NOT NULL,
  PRIMARY KEY (`Onoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brabeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brabeio` (
  `Onoma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Onoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pantheon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pantheon` (
  `Skinothetis_idSkinothetis` INT NOT NULL,
  `Thesi Skinotheti` INT NOT NULL,
  PRIMARY KEY (`Skinothetis_idSkinothetis`),
  CONSTRAINT `fk_Πάνθεον_Σκηνοθέτης1`
    FOREIGN KEY (`Skinothetis_idSkinothetis`)
    REFERENCES `mydb`.`Skinothetis` (`idSkinothetis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tainia_has_Xorhgos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tainia_has_Xorhgos` (
  `Tainia_Titlos` VARCHAR(45) NOT NULL,
  `Xorhgos_idXorhgos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tainia_Titlos`, `Xorhgos_idXorhgos`),
  INDEX `fk_Ταινία_has_Χορηγός_Χορηγός1_idx` (`Xorhgos_idXorhgos` ASC) VISIBLE,
  INDEX `fk_Ταινία_has_Χορηγός_Ταινία1_idx` (`Tainia_Titlos` ASC) VISIBLE,
  CONSTRAINT `fk_Ταινία_has_Χορηγός_Ταινία1`
    FOREIGN KEY (`Tainia_Titlos`)
    REFERENCES `mydb`.`Tainia` (`Titlos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ταινία_has_Χορηγός_Χορηγός1`
    FOREIGN KEY (`Xorhgos_idXorhgos`)
    REFERENCES `mydb`.`Xorhgos` (`idXorhgos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skhniko_has_Egxwria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skhniko_has_Egxwria` (
  `Skhniko_idSkhniko` VARCHAR(45) NOT NULL,
  `Egxwria_Tainia_Titlos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Skhniko_idSkhniko`, `Egxwria_Tainia_Titlos`),
  INDEX `fk_Σκηνικό_has_Εγχώρια_Εγχώρια1_idx` (`Egxwria_Tainia_Titlos` ASC) VISIBLE,
  INDEX `fk_Σκηνικό_has_Εγχώρια_Σκηνικό1_idx` (`Skhniko_idSkhniko` ASC) VISIBLE,
  CONSTRAINT `fk_Σκηνικό_has_Εγχώρια_Σκηνικό1`
    FOREIGN KEY (`Skhniko_idSkhniko`)
    REFERENCES `mydb`.`Skhniko` (`idSkhniko`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Σκηνικό_has_Εγχώρια_Εγχώρια1`
    FOREIGN KEY (`Egxwria_Tainia_Titlos`)
    REFERENCES `mydb`.`Egxwria` (`Tainia_Titlos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ithopoios_has_Xaraktiristiko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ithopoios_has_Xaraktiristiko` (
  `Ithopoios_Photografia` BLOB NOT NULL,
  `Xaraktiristiko_Onoma` VARCHAR(45) NOT NULL,
  `Bathmos xaraktiristikou` INT NOT NULL,
  PRIMARY KEY (`Ithopoios_Photografia`, `Xaraktiristiko_Onoma`),
  INDEX `fk_Ηθοποιός_has_Χαρακτηριστικό_Χαρ_idx` (`Xaraktiristiko_Onoma` ASC) VISIBLE,
  INDEX `fk_Ηθοποιός_has_Χαρακτηριστικό_Ηθο_idx` (`Ithopoios_Photografia` ASC) VISIBLE,
  CONSTRAINT `fk_Ηθοποιός_has_Χαρακτηριστικό_Ηθοπ1`
    FOREIGN KEY (`Ithopoios_Photografia`)
    REFERENCES `mydb`.`Ithopoios` (`Photografia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ηθοποιός_has_Χαρακτηριστικό_Χαρα1`
    FOREIGN KEY (`Xaraktiristiko_Onoma`)
    REFERENCES `mydb`.`Xaraktiristiko` (`Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagwnistikh diorganwsh_has_Brabeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagwnistikh diorganwsh_has_Brabeio` (
  `Diagwnistikh diorganwsh_Onoma` VARCHAR(45) NOT NULL,
  `Brabeio_Onoma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Diagwnistikh diorganwsh_Onoma`, `Brabeio_Onoma`),
  INDEX `fk_Διαγωνιστική διοργάνωση_has_Βρα_idx` (`Brabeio_Onoma` ASC) VISIBLE,
  INDEX `fk_Διαγωνιστική διοργάνωση_has_Βρα_idx1` (`Diagwnistikh diorganwsh_Onoma` ASC) VISIBLE,
  CONSTRAINT `fk_Διαγωνιστική διοργάνωση_has_Βραβ1`
    FOREIGN KEY (`Diagwnistikh diorganwsh_Onoma`)
    REFERENCES `mydb`.`Diagwnistikh diorganwsh` (`Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Διαγωνιστική διοργάνωση_has_Βραβ2`
    FOREIGN KEY (`Brabeio_Onoma`)
    REFERENCES `mydb`.`Brabeio` (`Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tainia_Diagwnistikh diorganwsh_Brabeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tainia_Diagwnistikh diorganwsh_Brabeio` (
  `Tainia_Titlos` VARCHAR(45) NOT NULL,
  `Diagwnistikh diorganwsh_has_Brabeio_Diagwnistikh diorganwsh_Onoma` VARCHAR(45) NOT NULL,
  `Diagwnistikh diorganwsh_has_Brabeio_Brabeio_Onoma` VARCHAR(45) NOT NULL,
  `Ypopsifiothta` TINYINT NOT NULL,
  `Nikh` TINYINT NOT NULL,
  PRIMARY KEY (`Tainia_Titlos`, `Diagwnistikh diorganwsh_has_Brabeio_Diagwnistikh diorganwsh_Onoma`, `Diagwnistikh diorganwsh_has_Brabeio_Brabeio_Onoma`),
  INDEX `fk_Ταινία_has_Διαγωνιστική διοργάν_idx` (`Diagwnistikh diorganwsh_has_Brabeio_Diagwnistikh diorganwsh_Onoma` ASC, `Diagwnistikh diorganwsh_has_Brabeio_Brabeio_Onoma` ASC) VISIBLE,
  INDEX `fk_Ταινία_has_Διαγωνιστική διοργάν_idx1` (`Tainia_Titlos` ASC) VISIBLE,
  CONSTRAINT `fk_Ταινία_has_Διαγωνιστική διοργάνω1`
    FOREIGN KEY (`Tainia_Titlos`)
    REFERENCES `mydb`.`Tainia` (`Titlos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ταινία_has_Διαγωνιστική διοργάνω2`
    FOREIGN KEY (`Diagwnistikh diorganwsh_has_Brabeio_Diagwnistikh diorganwsh_Onoma` , `Diagwnistikh diorganwsh_has_Brabeio_Brabeio_Onoma`)
    REFERENCES `mydb`.`Diagwnistikh diorganwsh_has_Brabeio` (`Diagwnistikh diorganwsh_Onoma` , `Brabeio_Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skinothetis_Xwra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skinothetis_Xwra` (
  `Skinothetis_idSkinothetis` INT NOT NULL,
  `Xwra_Onoma` VARCHAR(45) NOT NULL,
  `Ethnikothta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Skinothetis_idSkinothetis`, `Xwra_Onoma`),
  INDEX `fk_Σκηνοθέτης_has_Χώρα_Χώρα1_idx` (`Xwra_Onoma` ASC) VISIBLE,
  INDEX `fk_Σκηνοθέτης_has_Χώρα_Σκηνοθέτης1_idx` (`Skinothetis_idSkinothetis` ASC) VISIBLE,
  CONSTRAINT `fk_Σκηνοθέτης_has_Χώρα_Σκηνοθέτης1`
    FOREIGN KEY (`Skinothetis_idSkinothetis`)
    REFERENCES `mydb`.`Skinothetis` (`idSkinothetis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Σκηνοθέτης_has_Χώρα_Χώρα1`
    FOREIGN KEY (`Xwra_Onoma`)
    REFERENCES `mydb`.`Xwra` (`Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Xwra_Ithopoios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Xwra_Ithopoios` (
  `Xwra_Onoma` VARCHAR(45) NOT NULL,
  `Ithopoios_Photografia` BLOB NOT NULL,
  PRIMARY KEY (`Xwra_Onoma`, `Ithopoios_Photografia`),
  INDEX `fk_Χώρα_has_Ηθοποιός_Ηθοποιός1_idx` (`Ithopoios_Photografia` ASC) VISIBLE,
  INDEX `fk_Χώρα_has_Ηθοποιός_Χώρα1_idx` (`Xwra_Onoma` ASC) VISIBLE,
  CONSTRAINT `fk_Χώρα_has_Ηθοποιός_Χώρα1`
    FOREIGN KEY (`Xwra_Onoma`)
    REFERENCES `mydb`.`Xwra` (`Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Χώρα_has_Ηθοποιός_Ηθοποιός1`
    FOREIGN KEY (`Ithopoios_Photografia`)
    REFERENCES `mydb`.`Ithopoios` (`Photografia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Μixani AI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Μixani AI` (
  `idMixani AI` VARCHAR(45) NOT NULL,
  `Keimeno grafhs_idKeimeno grafhs` LONGTEXT NOT NULL,
  PRIMARY KEY (`idMixani AI`, `Keimeno grafhs_idKeimeno grafhs`),
  INDEX `fk_Μηχανή AI_Κείμενο γραφής1_idx` (`Keimeno grafhs_idKeimeno grafhs` ASC) VISIBLE,
  CONSTRAINT `fk_Μηχανή AI_Κείμενο γραφής1`
    FOREIGN KEY (`Keimeno grafhs_idKeimeno grafhs`)
    REFERENCES `mydb`.`Keimeno grafhs` (`idKeimeno grafhs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rolos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rolos` (
  `idRolos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRolos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tainia_has_Ithopoios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tainia_has_Ithopoios` (
  `Tainia_Titlos` VARCHAR(45) NOT NULL,
  `Ithopoios_photografia` BLOB NOT NULL,
  `Symbolaio_idSymbolaio` VARCHAR(45) NOT NULL,
  `Rolos_idRolos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tainia_Titlos`, `Ithopoios_photografia`, `Symbolaio_idSymbolaio`, `Rolos_idRolos`),
  INDEX `fk_Ταινία_has_Ηθοποιός_Ηθοποιός1_idx` (`Ithopoios_photografia` ASC) VISIBLE,
  INDEX `fk_Ταινία_has_Ηθοποιός_Ταινία1_idx` (`Tainia_Titlos` ASC) VISIBLE,
  INDEX `fk_Ταινία_has_Ηθοποιός_Συμβόλαιο1_idx` (`Symbolaio_idSymbolaio` ASC) VISIBLE,
  INDEX `fk_Ταινία_has_Ηθοποιός_Ρόλος1_idx` (`Rolos_idRolos` ASC) VISIBLE,
  CONSTRAINT `fk_Ταινία_has_Ηθοποιός_Ταινία1`
    FOREIGN KEY (`Tainia_Titlos`)
    REFERENCES `mydb`.`Tainia` (`Titlos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ταινία_has_Ηθοποιός_Ηθοποιός1`
    FOREIGN KEY (`Ithopoios_photografia`)
    REFERENCES `mydb`.`Ithopoios` (`Photografia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ταινία_has_Ηθοποιός_Συμβόλαιο1`
    FOREIGN KEY (`Symbolaio_idSymbolaio`)
    REFERENCES `mydb`.`Symbolaio` (`idSymbolaio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ταινία_has_Ηθοποιός_Ρόλος1`
    FOREIGN KEY (`Rolos_idRolos`)
    REFERENCES `mydb`.`Rolos` (`idRolos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Texniko xaraktiristiko_Programma ekpaidefsis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Texniko xaraktiristiko_Programma ekpaidefsis` (
  `Texniko xaraktiristiko_Xaraktiristiko_Onoma` VARCHAR(45) NOT NULL,
  `Programma ekpaidefsis_idProgramma ekpaidefsis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Texniko xaraktiristiko_Xaraktiristiko_Onoma`, `Programma ekpaidefsis_idProgramma ekpaidefsis`),
  INDEX `fk_Τεχνικό χαρακτηριστικό_has_Πρόγ_idx` (`Programma ekpaidefsis_idProgramma ekpaidefsis` ASC) VISIBLE,
  INDEX `fk_Τεχνικό χαρακτηριστικό_has_Πρόγ_idx1` (`Texniko xaraktiristiko_Xaraktiristiko_Onoma` ASC) VISIBLE,
  CONSTRAINT `fk_Τεχνικό χαρακτηριστικό_has_Πρόγρ1`
    FOREIGN KEY (`Texniko xaraktiristiko_Xaraktiristiko_Onoma`)
    REFERENCES `mydb`.`Texniko xaraktiristiko` (`Xaraktiristiko_Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Τεχνικό χαρακτηριστικό_has_Πρόγρ2`
    FOREIGN KEY (`Programma ekpaidefsis_idProgramma ekpaidefsis`)
    REFERENCES `mydb`.`Programma ekpaidefsis` (`idProgramma ekpaidefsis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ithopoios_Programma ekpaidefsis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ithopoios_Programma ekpaidefsis` (
  `Ithopoios_Photografia` BLOB NOT NULL,
  `Programma ekpaidefsis_idProgramma ekpaidefsis` VARCHAR(45) NOT NULL,
  `Parakolouthisi` TINYINT NOT NULL,
  PRIMARY KEY (`Ithopoios_Photografia`, `Programma ekpaidefsis_idProgramma ekpaidefsis`),
  INDEX `fk_Ηθοποιός_has_Πρόγραμμα εκπαίδευ_idx` (`Programma ekpaidefsis_idProgramma ekpaidefsis` ASC) VISIBLE,
  INDEX `fk_Ηθοποιός_has_Πρόγραμμα εκπαίδευ_idx1` (`Ithopoios_Photografia` ASC) VISIBLE,
  CONSTRAINT `fk_Ηθοποιός_has_Πρόγραμμα εκπαίδευσ1`
    FOREIGN KEY (`Ithopoios_Photografia`)
    REFERENCES `mydb`.`Ithopoios` (`Photografia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ηθοποιός_has_Πρόγραμμα εκπαίδευσ2`
    FOREIGN KEY (`Programma ekpaidefsis_idProgramma ekpaidefsis`)
    REFERENCES `mydb`.`Programma ekpaidefsis` (`idProgramma ekpaidefsis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Koinwniko diktio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Koinwniko diktio` (
  `Onoma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Onoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Koinwniko diktio_Tainia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Koinwniko diktio_Tainia` (
  `Tainia_Titlos` VARCHAR(45) NOT NULL,
  `Koinwniko diktio_Onoma` VARCHAR(45) NOT NULL,
  `Likes` INT NOT NULL,
  PRIMARY KEY (`Tainia_Titlos`, `Koinwniko diktio_Onoma`),
  INDEX `fk_Κοινωνικό δίκτυο_Ταινία1_idx` (`Tainia_Titlos` ASC) VISIBLE,
  INDEX `fk_Κοινωνικό δίκτυο_table11_idx` (`Koinwniko diktio_Onoma` ASC) VISIBLE,
  CONSTRAINT `fk_Κοινωνικό δίκτυο_Ταινία1`
    FOREIGN KEY (`Tainia_Titlos`)
    REFERENCES `mydb`.`Tainia` (`Titlos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Κοινωνικό δίκτυο_table11`
    FOREIGN KEY (`Koinwniko diktio_Onoma`)
    REFERENCES `mydb`.`Koinwniko diktio` (`Onoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
